[project]
name = "backup-me"
version = "0.1.0"
readme = "README.md"
authors = [{ name = "bastantoine", email = "dev@bastien-antoine.fr" }]
requires-python = ">=3.14"
dependencies = ["boto3", "typer[all]", "pydantic", "requests"]

[project.optional-dependencies]
tests = [
    "pytest",
    "coverage",
    "pytest-subprocess",
    "pytest-mock",
    "moto[s3]",
    "requests-mock",
]

[project.scripts]
backup-me = 'backup_me.main:console'

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
